version: '3.8'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strapi_app
    restart: always
    ports:
      - '1337:1337'
    env_file:
      - .env
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapi_user
      DATABASE_PASSWORD: strapi_password

  db:
    image: postgres:15-alpine
    container_name: strapi_db
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: strapi_db
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: strapi_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
