version: '3.8'

services:
  strapi:
    image: yourusername/strapi-app:latest
    container_name: strapi_app
    restart: always
    ports:
      - '1337:1337'
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapi_user
      DATABASE_PASSWORD: strapi_password
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: strapi_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: strapi_db
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: strapi_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
