name: Deploy Strapi build

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      deployments: write
    name: Strapi deployment
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Dump database postgres sql
        run: pg_dump -h 127.0.0.1 -p 5432 -U username -d unicode_prod  -f backup.sql

      - name: Upload backup as artifact
        uses: actions/upload-artifact@v2
        with:
          name: backup
          path: backup.sql

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:prod
        env:
          PUBLIC_CMS_KEY: ${{ secrets.PUBLIC_CMS_KEY }}
          PIRIVATE_CMS_KEY: ${{ secrets.PIRIVATE_CMS_KEY }}
          PUBLIC_API_URL: ${{ secrets.PUBLIC_API_URL }}
          PUBLIC_IMG_URL: ${{ secrets.PUBLIC_IMG_URL }}
