name: Deploy Strapi build

on:
  push:
    branches: ['production']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    name: Strapi deployment
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/strapi-api:prod

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/strapi-api:prod
            docker stop strapi-api:prod || true
            docker rm strapi-api:prod || true
            docker run -d --name strapi-api:prod -p 1337:1337 --network="host" --env-file .env ${{ secrets.DOCKERHUB_USERNAME }}/strapi-api:prod
