name: Deploy Strapi build

on:
  push:
    branches: ['production']
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      deployments: write
    name: Create config file
    steps:
      - name: Create env file
        run: |
          touch .env

      - name: Configure Server
        run: |
          echo "HOST=0.0.0.0" >> .env
          echo "PORT=1337" >> .env

      - name: Configure Secrets
        run: |
          echo "APP_KEYS=${{ secrets.APP_KEYS }}" >> .env
          echo "API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }}" >> .env
          echo "ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}" >> .env
          echo "TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Configure DataBase
        run: |
          echo "DATABASE_CLIENT=${{ secrets.DATABASE_CLIENT }}" >> .env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_SSL=${{ secrets.DATABASE_SSL }}" >> .env
          echo "DATABASE_FILENAME=${{ secrets.DATABASE_FILENAME }}" >> .env

      - name: Configure Cloudflare R2 & CDN
        run: |
          echo "CF_ACCESS_KEY_ID=${{ secrets.CF_ACCESS_KEY_ID }}" >> .env
          echo "CF_ACCESS_SECRET=${{ secrets.CF_ACCESS_SECRET }}" >> .env
          echo "CF_PUBLIC_ACCESS_URL=${{ secrets.CF_PUBLIC_ACCESS_URL }}" >> .env
          echo "CF_BUCKET=${{ secrets.CF_BUCKET }}" >> .env
          echo "CF_ENDPOINT=${{ secrets.CF_ENDPOINT }}" >> .env

      - name: Upload .env file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: .env

  build:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      deployments: write
    name: Strapi deployment
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download .env file
        uses: actions/download-artifact@v4
        with:
          name: env-file

      - name: Dump database postgres sql
        run: pg_dump -h 127.0.0.1 -p 5432 -U username -d unicode_prod  -f backup.sql

      - name: Upload backup as artifact
        uses: actions/upload-artifact@v2
        with:
          name: backup
          path: backup.sql

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push the Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max

    #  - name: Deploy
    #    run:
